apiVersion: v1
kind: Service
metadata:
  name: {{ include "litellm-triage.fullname" . }}-ollama
  labels:
    {{- include "litellm-triage.ollama.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ollama.service.type }}
  ports:
    - port: {{ .Values.ollama.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "litellm-triage.ollama.selectorLabels" . | nindent 4 }}
